type: overfit
trainer: stage_inr
dataset:
  type: shapenet
  folder: /home/umaru/praktikum/changed_version/ginr-ipc/data/shapenet/overfit/1a6ad7a24bb89733f412783097373bdc.obj.npy
  transforms:
    type: shapenet

arch: # needs to add encoder, modulation type
  type: meta_low_rank_modulated_inr
  ema: null

  rank: [128] # list, assert len(n_weight_groups) in [1, hyponet.n_layer]
  modulated_layer_idxs: [1,3]
  use_factorization:  true

  n_inner_step: 4
  inner_lr: 0.003


  coord_sampler:
    data_type: image
    coord_range: [-1.0, 1.0]
    train_strategy: null
    val_strategy: null

  hyponet:
    type: mlp
    n_layer: 6 # including the output layer
    hidden_dim: [256,256,256,256,128] # list, assert len(hidden_dim) in [1, n_layers-1]
    use_bias: true
    input_dim: 3
    output_dim: 1
    output_bias: 0.5
    fourier_mapping:
      type: 3d
      trainable: false
      use_ff: true
      ff_sigma: 7 # ff_dim = 2*ff_sigma *3 + (3)
      ff_dim: 45

    activation:
      type: relu
      siren_w0: null
    initialization:
      weight_init_type: kaiming_uniform
      bias_init_type: zero
    normalize_weight: true

loss:
  type: mse #now unnecessary
  subsample:
    type: null
    ratio: 0.1
  coord_noise: null

optimizer:
  type: overfit
  init_lr: 0.001
  weight_decay: 0.5

  betas: [0.9, 0.95] #[0.9, 0.95]
  warmup:
    epoch: 0
    multiplier: 1
    buffer_epoch: 0
    min_lr: 0.000001
    mode: adaptive
    step_size: 30
    gamma: 0.1
    patience: 30
    patience_adaptive: 200
    factor: 0.8
    threshold: 0
    start_from_zero: True
  max_gn: null

experiment:
  amp: True
  batch_size: 80
  total_batch_size: 80
  epochs: 400
  epochs_cos: 30
  save_ckpt_freq: 50
  test_freq: 30
  test_imlog_freq: 100

