type: overfit
trainer: stage_inr
dataset:
  type: shapenet
  folder: data/shapenet/single_fit/3e0561d70c7fd4f51c6e4e20f2b76086.obj.npy
  transforms:
    type: shapenet

arch: # needs to add encoder, modulation type
  type: meta_low_rank_modulated_inr
  ema: null

  rank: [128] # list, assert len(n_weight_groups) in [1, hyponet.n_layer]
  modulated_layer_idxs: [1]
  use_factorization: true

  n_inner_step: 4
  inner_lr: 0.003


  coord_sampler:
    data_type: image
    coord_range: [-1.0, 1.0]
    train_strategy: null
    val_strategy: null

  hyponet:
    type: mlp
    n_layer: 6 # including the output layer
    hidden_dim: [256,256,256,128,128] # list, assert len(hidden_dim) in [1, n_layers-1]
    use_bias: true
    input_dim: 3
    output_dim: 1
    output_bias: 0.5
    fourier_mapping:
      type: 3d
      trainable: false
      use_ff: true
      ff_sigma: 4 # ff_dim = 2*ff_sigma *3 + (3)
      ff_dim: 27

    activation:
      type: relu
      siren_w0: null
    initialization:
      weight_init_type: kaiming_uniform
      bias_init_type: zero
    normalize_weight: true

loss:
  type: mse #now unnecessary
  subsample:
    type: null
    ratio: 0.1
  coord_noise: null

optimizer:
  type: overfit
  init_lr: 0.00001
  weight_decay: 0.00001
  betas: [0.9, 0.95] #[0.9, 0.95]
  warmup:
    epoch: 0
    multiplier: 1
    buffer_epoch: 0
    min_lr: 0.000000001
    mode: fix
    start_from_zero: True
  max_gn: null

experiment:
  amp: True
  batch_size: 2000
  total_batch_size: 2000
  epochs: 300
  epochs_cos: 30
  save_ckpt_freq: 20
  test_freq: 20
  test_imlog_freq: 10

