
trainer: stage_inr
dataset:
  type: shapenet
  folder: ./data/shapenet
  transforms:
    type: shapenet

arch: # needs to add encoder, modulation type
  type: meta_low_rank_modulated_inr
  ema: null

  rank: [128] # list, assert len(n_weight_groups) in [1, hyponet.n_layer]
  modulated_layer_idxs: [1]
  use_factorization: false

  n_inner_step: 3
  inner_lr: 0.003


  coord_sampler:
    data_type: image
    coord_range: [-1.0, 1.0]
    train_strategy: null
    val_strategy: null

  hyponet:
    type: mlp
    n_layer: 4 # including the output layer
    hidden_dim: [128] # list, assert len(hidden_dim) in [1, n_layers-1]
    use_bias: true
    input_dim: 3
    output_dim: 1
    output_bias: 0.5
    fourier_mapping:
      type: 3d
      trainable: false
      use_ff: true
      ff_sigma: 4 # ff_dim = 2*ff_sigma *3 + (3)
      ff_dim: 27

    activation:
      type: relu
      siren_w0: null
    initialization:
      weight_init_type: kaiming_uniform
      bias_init_type: zero
    normalize_weight: true

loss:
  type: mse #now unnecessary
  subsample:
    type: null
    ratio: 0.1
  coord_noise: null

optimizer:
  type: adam
  init_lr: 0.0001
  weight_decay: 0.1
  betas: [0.9, 0.95] #[0.9, 0.95]
  warmup:
    epoch: 0
    multiplier: 1
    buffer_epoch: 0
    min_lr: 0.0001
    mode: fix
    start_from_zero: True
  max_gn: null

experiment:
  amp: True
  batch_size: 1
  total_batch_size: 1
  epochs: 5000
  epochs_cos: 2500
  save_ckpt_freq: 2000
  test_freq: 100
  test_imlog_freq: 300

